### ISSUE TITLE
Invalid comment when converting Sass to SCSS

### ISSUE THREAD

**Issue by KittyGiraudel** [sass/sass#1398]
When converting `.sass` to `.scss`, C-style comments break.

``` scss
/**
 * Comment
 */
```

Results in:

``` sass
/**
 * Comment
```

**Comment by pascalduez** [comment]
Actually the issue we have on SassDoc/sassdoc#183 is on converting from `.sass` to `.scss`

See https://github.com/pascalduez/sassdoc-convert

The command used is `npm test` as declared [here](https://github.com/pascalduez/sassdoc-convert/blob/master/package.json#L12-L14)

**Comment by stevenleeg** [comment]
+1. Would be great to see this fixed in order to get `.sass` working in the sassdoc project.

**Comment by nex3** [comment]
I can't reproduce this:

```
$ ./bin/sass-convert --version
Sass 3.4.1.09c8af1 (Selective Steve)
$ ./bin/sass-convert --from sass --to scss <<SASS
/*
 * Comment
 */
SASS

/* Comment
 */
```

**Comment by KittyGiraudel** [comment]
We used this syntax to convert &mdash;as mentioned in [Sass official' docs](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#syntax): 

``` rb
sass-convert sass/indented.sass scss/sassy.scss
```

So maybe we need to try with what you suggest. Is there a specific documentation for this somewhere?

Ping @pascalduez.

**Comment by nex3** [comment]
I can reproduce it when using a file directly. Very curious.

**Comment by nex3** [comment]
It looks like the problem is that `sass-convert` is failing to infer the output format from the filename.

**Comment by KittyGiraudel** [comment]
Oh. Glad you could reproduce it anyway. If you need us to run some extra tests, be sure to ask.

**Comment by nex3** [comment]
Fixed by 0f06861675551a60cb8738719011ded8a1fbad26.

**Comment by KittyGiraudel** [comment]
Sass 3.4.3 on SassMeister: when converting from SCSS to Sass, I am still facing broken comments.

**Step 1.** `sample.scss`:

``` scss
/**
 * This is a docblock comment
 */ 
```

**Step 2.** Converting to `.sass`:

``` sass
/**
 * This is a docblock comment
```

**Step 3.** Converting back to `.scss`:

``` scss
/*
 * This is a docblock comment */
```

Converting back to `.sass` go back to step 2.

**Comment by nex3** [comment]
@HugoGiraudel All those comments look fine to me (modulo #1432). What's wrong with them?

**Comment by KittyGiraudel** [comment]
Comment from step 2 is broken: it's not closed.
Comment from step 3 is not the same as the first one, especially the opening.

**Comment by nex3** [comment]
> Comment from step 2 is broken: it's not closed.

Comments aren't required to be closed in the indented syntax. They're indentation-based like everything else.

> Comment from step 3 is not the same as the first one, especially the opening.

The opening is tracked by #1432. In general we don't guarantee formatting equivalence when doing conversions, especially for round-trips through other syntaxes.

**Comment by KittyGiraudel** [comment]
> Comments aren't required to be closed in the indented syntax. They're indentation-based like everything else.

I didn't know about this. My bad then.

> The opening is tracked by #1432. In general we don't guarantee formatting equivalence when doing conversions, especially for round-trips through other syntaxes.

Let's move the conversation there then.
