### ISSUE TITLE
Sass 3.4.17 not adding semicolon

### ISSUE THREAD

**Issue by radu-matei** [sass/sass#1806]
I have just installed Sass 3.4.17 Selective Steve and when creating my main.min.css it doesn't add semicolons after the first two imports.

I saw in the changelog that there was a fix related to semicolons, so I believe the issues are related.
Until there is a fix, I rolled back to 3.4.16.

**Comment by chriseppstein** [comment]
Can you please provide a code example of what's broken?

**Comment by radu-matei** [comment]
@import url("../../node_modules/bootstrap/dist/css/bootstrap.min.css")@import url("../../node_modules/font-awesome/css/font-awesome.min.css") etc

Notice how after the first import the semicolon is missing, even though in the initial css it was there. So was the case after the second import.

**Comment by chriseppstein** [comment]
I cannot reproduce this. Please provide a minimal code example and the commands you're using to compile it.

**Comment by radu-matei** [comment]
This is the command I use: 
cmd.exe /c grunt -b "C:\Users..." --gruntfile "C:\Users...Gruntfile.js" sass:dist  

And this is part of the file that needs to be processed:
@charset "utf-8";

/_:::: Main Stylesheet ::::_/
$image-path: "../..";

@import 'reset.scss';
@import url("../../node_modules/bootstrap/dist/css/bootstrap.min.css");
@import url("../../node_modules/font-awesome/css/font-awesome.min.css");

Now, when the processing is complete, those semicolons (all 3) are missing.

And this is the grunt  task I use:

```
    sass: {
        dist: {
            options: {
                style: 'compressed'
            },
            files: [
              {
                  expand: true,
                  cwd: 'Content/sass',
                  src: ["**/main.scss"],
                  dest: "Content/css",
                  ext: ".min.css"
              }
            ]
        }
    }
```

**Comment by robchenski** [comment]
I'm getting exactly the same behaviour with Sass 3.4.17 Selective Steve. With compressed output style.

@import url(MyFontsWebfontsKit.css)html{font-size:62.5%} etc.

no semicolon after @import url()

It's stopping my fonts from loading! No console errors either.

It was fine before I moved / ugraded my dev env. 
Only just installed this too in a new dev environment and probably got all newer versions than what I previously had in my last setup. 

As a workaround and to save trawling about for the problem I've changed output style to 'expanded'. Which is not ideal but gets me out of a tight spot.

Here's my options and style that causes the problem etc:

sass : {
    dist : {
        options : {
            style : 'compressed'
        },
        files : {
            'css/main.css' : 'sass/main.scss'
        }
    }
}

@import 'MyFontsWebfontsKit.css';
html {
  box-sizing: border-box;
  font-size: 62.5%;
}

I'll wait and see what happens here..

**Comment by chriseppstein** [comment]
Fixed in 3.4.18 which was just released.

**Comment by robchenski** [comment]
Working for me in 3.4.18 ! 
Thanx and darn quick too.. Good skills

**Comment by marschro** [comment]
have this issue still in 3.4.21 (critical steve)

```
@mixin device($media) {
  @if $media == mobile {
    @media only screen and (max-width: 375px) { @content; }
  }
  @else if $media == tablets {
    @media only screen and (min-width: 376px) and (max-width: 768px) { @content; }
  }
  @else if $media == desktop {
    @media only screen and (min-width: 769px) { @content; }
  }
}
```

Using:
```
@include device(mobile) {font-size: 12em;}
```
Parses to:
```
@media only screen and (max-width: 375px){
    h1{
        font-size:12em
    }
}
```

UPDATE:
Only happens when sass --style compressed 
bummer...

**Comment by xzyfer** [comment]
@marschro the trailing semicolon on the last declaration is not needed in CSS so it was left out as an optimisation.
